### ISSUE TITLE
Coomzy has apparently missed his mod becoming super popular

### ISSUE THREAD

**Issue by invicta-nz** [Coomzy/Pavlov-Rush#1]
Ok, so not really an issue, but more of an heads up that this mod has become one of the most popular Pavlov modes after recent updates to game chooser has made popular Community servers show up at top of list. Hope is to bring your attention to this and draw you back into helping us make it better. Will submit some real issues with a real report

**Comment by Coomzy** [comment]
Hey there, thanks for posting this but I've spoken to some people so I've heard this has gained some popularity. I won't be returning to the mod. However if anyone wants to pick it up and take it on they are welcome to do that, they can drop a message on here and I will add them as a contributor and they are free to make any changes they want.

**Comment by invicta-nz** [comment]
Thanks again for making this mod... lots of players have said it was the best thing they have played in Pav yet. Just needed some players to find it.
